name: blueprints

on:
  push:
    branches:
      - main
      - views
  pull_request:
    branches:
      - main
      - views

jobs:
  build:
    runs-on: macos-latest # Needed for emulators
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project and UnitTest
        run: ./gradlew assembleDebug compileDebugUnitTestKotlin

      - name: Spotless
        run: ./gradlew spotlessCheck

      - name: Robolectric
        run: ./gradlew testDebugUnitTest

      # Needed to accept licenses
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Compile AndroidTests
        run: ./gradlew compileDebugAndroidTestKotlin

      - name: Run all tests pixel 2 api 30 ATD
        working-directory: .
        run: ./gradlew -Pandroid.sdk.channel=3 -Pandroid.experimental.androidTest.numManagedDeviceShards=1 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" pixel2api30atdDebugAndroidTest

      - name: Run all tests pixel 2 api 30 non-ATD
        working-directory: .
        run: ./gradlew -Pandroid.sdk.channel=3 -Pandroid.experimental.androidTest.numManagedDeviceShards=1 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" pixel2api30DebugAndroidTest

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: app/build/reports/

      - name: Upload all outputs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: app/build/outputs/
